name: Gitea Actions Test
run-name: ${{ github.actor }} is testing out Gitea Actions ğŸš€
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  Runner-Check:
    runs-on: ubuntu-latest
    steps:
      - name: List job trigger
        run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: List runner OS
        run: echo "ğŸ§ This job is now running on an ${{ runner.os }} amd64 server."
      
      - name: Get branch
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: List environment variables
        run: env
      
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Verify repo cloned
        run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Check if runner is ready for testing code
        run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: List job status
        run: echo "ğŸ This job's status is ${{ job.status }}."
